# Generated by Django 2.1 on 2018-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('tweet_text', models.TextField()),
                ('user_name', models.CharField(max_length=256)),
                ('user_screen_name', models.CharField(max_length=256)),
                ('retweet_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
